# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "funasr"
backend: "python"
max_batch_size: 16

parameters [
  {
    key: "model_dir"
    value: {string_value: "FunAudioLLM/Fun-ASR-Nano-2512"}
  },
  {
    key: "vllm_model_dir"
    value: {string_value: "yuekai/Fun-ASR-Nano-2512-vllm"}
  },
  {
    key: "encoder_trt_engine"
    value: {string_value: ""}
  },
  {
    key: "device"
    value: {string_value: "cuda:0"}
  },
  {
    key: "llm_dtype"
    value: {string_value: "bfloat16"}
  },
  {
    key: "gpu_memory_utilization"
    value: {string_value: "0.4"}
  }
]

input [
  {
    name: "WAV"
    data_type: TYPE_FP32
    dims: [-1]
  },
  {
    name: "WAV_LENS"
    data_type: TYPE_INT32
    dims: [1]
    optional: true
  }
]

output [
  {
    name: "TRANSCRIPTS"
    data_type: TYPE_STRING
    dims: [1]
  }
]

dynamic_batching {
  max_queue_delay_microseconds: 5000
}

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [0]
  }
]
